Make Makejail compatible with Apache and PHP-FPM

diff --git a/Makejail b/Makejail
--- a/Makejail
+++ b/Makejail
@@ -25,41 +25,49 @@ ARG wp_debug=0
 # Tag
 ARG wp_tag=13.2-php82-apache-6.2.2
 
-FROM --entrypoint gh+AppJail-makejails/wordpress wordpress:${wp_tag}
+FROM --entrypoint /tmp/m/wordpress/.ajspec wordpress:${wp_tag}
 
-COPY wp-config-sample.php /usr/local/www/wordpress/wp-config.php
+RAW if appjail cmd jexec "${APPJAIL_JAILNAME}" [ -d "/usr/local/www/wordpress" ]; then
+	VAR --make-arg-env wwwdir=/usr/local/www/wordpress
+RAW elif appjail cmd jexec "${APPJAIL_JAILNAME}" [ -d "/usr/local/www/apache24/data" ]; then
+	VAR --make-arg-env wwwdir=/usr/local/www/apache24/data
+RAW else
+	RAW echo "Cannot find a WWW directory." >&2
+	RAW exit 1
+RAW fi
+COPY wp-config-sample.php ${wwwdir}/wp-config.php
 
-REPLACE /usr/local/www/wordpress/wp-config.php DB_NAME ${wp_db_name}
-REPLACE /usr/local/www/wordpress/wp-config.php DB_USER ${wp_db_user}
+REPLACE ${wwwdir}/wp-config.php DB_NAME ${wp_db_name}
+REPLACE ${wwwdir}/wp-config.php DB_USER ${wp_db_user}
 
-REPLACE /usr/local/www/wordpress/wp-config.php DB_PASSWORD ${wp_db_password}
+REPLACE ${wwwdir}/wp-config.php DB_PASSWORD ${wp_db_password}
 
-REPLACE /usr/local/www/wordpress/wp-config.php DB_HOST ${wp_db_host}
-REPLACE /usr/local/www/wordpress/wp-config.php DB_CHARSET ${wp_db_charset}
+REPLACE ${wwwdir}/wp-config.php DB_HOST ${wp_db_host}
+REPLACE ${wwwdir}/wp-config.php DB_CHARSET ${wp_db_charset}
 
-REPLACE /usr/local/www/wordpress/wp-config.php DB_COLLATE ${wp_db_collate}
+REPLACE ${wwwdir}/wp-config.php DB_COLLATE ${wp_db_collate}
 
 RAW if [ "${wp_auto_secret}" = 0 ]; then
-	COPY wp-security-keys.php /usr/local/www/wordpress/wp-security-keys.php
+	COPY wp-security-keys.php ${wwwdir}/wp-security-keys.php
 
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php AUTH_KEY ${wp_auth_key}
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php SECURE_AUTH_KEY ${wp_secure_auth_key}
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php LOGGED_IN_KEY ${wp_logged_in_key}
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php NONCE_KEY ${wp_nonce_key}
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php AUTH_SALT ${wp_auth_salt}
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php SECURE_AUTH_SALT ${wp_secure_auth_salt}
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php LOGGED_IN_SALT ${wp_logged_in_salt}
-	REPLACE /usr/local/www/wordpress/wp-security-keys.php NONCE_SALT ${wp_nonce_salt}
+	REPLACE ${wwwdir}/wp-security-keys.php AUTH_KEY ${wp_auth_key}
+	REPLACE ${wwwdir}/wp-security-keys.php SECURE_AUTH_KEY ${wp_secure_auth_key}
+	REPLACE ${wwwdir}/wp-security-keys.php LOGGED_IN_KEY ${wp_logged_in_key}
+	REPLACE ${wwwdir}/wp-security-keys.php NONCE_KEY ${wp_nonce_key}
+	REPLACE ${wwwdir}/wp-security-keys.php AUTH_SALT ${wp_auth_salt}
+	REPLACE ${wwwdir}/wp-security-keys.php SECURE_AUTH_SALT ${wp_secure_auth_salt}
+	REPLACE ${wwwdir}/wp-security-keys.php LOGGED_IN_SALT ${wp_logged_in_salt}
+	REPLACE ${wwwdir}/wp-security-keys.php NONCE_SALT ${wp_nonce_salt}
 RAW else
-	CMD echo "<?php" > /usr/local/www/wordpress/wp-security-keys.php
-	CMD fetch -qo - "https://api.wordpress.org/secret-key/1.1/salt" >> /usr/local/www/wordpress/wp-security-keys.php
+	CMD echo "<?php" > ${wwwdir}/wp-security-keys.php
+	CMD fetch -qo - "https://api.wordpress.org/secret-key/1.1/salt" >> ${wwwdir}/wp-security-keys.php
 RAW fi
 
-REPLACE /usr/local/www/wordpress/wp-config.php TABLE_PREFIX ${wp_table_prefix}
+REPLACE ${wwwdir}/wp-config.php TABLE_PREFIX ${wp_table_prefix}
 
 RAW if [ "${wp_debug}" = 0 ]; then
 RAW 	wp_debug=false
 RAW else
 RAW 	wp_debug=true
 RAW fi
-REPLACE /usr/local/www/wordpress/wp-config.php DEBUG ${wp_debug}
+REPLACE ${wwwdir}/wp-config.php DEBUG ${wp_debug}
